name: validatPython

on:
  push:
    branches: [ "main"]
  workflow_dispatch:
  
jobs:
  verify:
    runs-on: ubunto-latest
    
    steps:
      - uses: action/checkout@v3
      
    
      - name: Setup Python
        uses: actions/setup-python@v4.3.1
 
